stocks = {'afks': 'https://ru.investing.com/equities/afk-sistema_rts-historical-data',
          'aflt': 'https://ru.investing.com/equities/aeroflot-historical-data',
          'agrodr': 'https://ru.investing.com/equities/ros-agro-plc-historical-data',
          'alrs': 'https://ru.investing.com/equities/alrosa-ao-historical-data',
          'cbom': 'https://ru.investing.com/equities/moskovskiy-kreditnyi-bank-oao-historical-data',
          'chmf': 'https://ru.investing.com/equities/severstal_rts-historical-data',
          'enpg': 'https://ru.investing.com/equities/en-plus-group-international-pao-historical-data',
          'fees': 'https://ru.investing.com/equities/fsk-ees_rts-historical-data',
          'fivedr': 'https://ru.investing.com/equities/x5-retail-grp-historical-data?cid=1061926',
          'flot': 'https://ru.investing.com/equities/sovcomflot-pao-historical-data',
          'gazp': 'https://ru.investing.com/equities/gazprom_rts-historical-data',
          'gltrdr': 'https://ru.investing.com/equities/globaltrans-inv-historical-data?cid=1167212',
          'gmkn': 'https://ru.investing.com/equities/gmk-noril-nickel_rts-historical-data',
          'hydr': 'https://ru.investing.com/equities/gidroogk-011d-historical-data',
          'irao': 'https://ru.investing.com/equities/inter-rao-ees_mm-historical-data',
          'lkoh': 'https://ru.investing.com/equities/lukoil_rts-historical-data',
          'magn': 'https://ru.investing.com/equities/mmk_rts-historical-data',
          'mgnt': 'https://ru.investing.com/equities/magnit_rts-historical-data',
          'msng': 'https://ru.investing.com/equities/mosenergo_rts-historical-data',
          'mtlr': 'https://ru.investing.com/equities/sg-mechel_rts-historical-data',
          'mtss': 'https://ru.investing.com/equities/mts_rts-historical-data',
          'nlmk': 'https://ru.investing.com/equities/nlmk_rts-historical-data',
          'nvtk': 'https://ru.investing.com/equities/novatek_rts-historical-data',
          'ozondr': 'https://ru.investing.com/equities/ozon-holdings-plc-historical-data',
          'phor': 'https://ru.investing.com/equities/phosagro-historical-data',
          'pikk': 'https://ru.investing.com/equities/pik_rts-historical-data',
          'plzl': 'https://ru.investing.com/equities/polyus-zoloto_rts-historical-data',
          'poly': 'https://ru.investing.com/equities/polymetal-historical-data',
          'posi': 'https://ru.investing.com/equities/gruppa-pozitiv-pao-historical-data',
          'rosn': 'https://ru.investing.com/equities/rosneft_rts-historical-data',
          'rtkm': 'https://ru.investing.com/equities/rostelecom-historical-data',
          'rual': 'https://ru.investing.com/equities/united-company-rusal-plc%60-historical-data',
          'sber': 'https://ru.investing.com/equities/sberbank_rts-historical-data',
          'selg': 'https://ru.investing.com/equities/seligdar-historical-data',
          'sgzh': 'https://ru.investing.com/equities/segezha-group-pao-historical-data',
          'smlt': 'https://ru.investing.com/equities/gk-samolet-pao-historical-data',
          'sngs': 'https://ru.investing.com/equities/surgutneftegas_rts-historical-data',
          'tatn': 'https://ru.investing.com/equities/tatneft_rts-historical-data',
          'tcsg': 'https://ru.investing.com/equities/tcs-group-holding-plc-historical-data',
          'trnf_p': 'https://ru.investing.com/equities/transneft-p_rts-historical-data',
          'upro': 'https://ru.investing.com/equities/e.on-russia-historical-data',
          'vkco': 'https://ru.investing.com/equities/mail.ru-grp-wi-historical-data',
          'vtbr': 'https://ru.investing.com/equities/vtb_rts-historical-data',
          'yndx': 'https://ru.investing.com/equities/yandex-historical-data?cid=102063',
          'qiwidr': 'https://ru.investing.com/equities/qiwi-plc-historical-data?cid=960754',
          'trmk': 'https://ru.investing.com/equities/tmk-historical-data',
          'akrn': 'https://ru.investing.com/equities/akron_rts-historical-data',
          'mgmdr': 'https://ru.investing.com/equities/md-medical-drc-historical-data',
          'utar': 'https://ru.investing.com/equities/utair-aviakompaniya-oao-historical-data'}

news = {'afks': 'https://www.finam.ru/quote/moex/afks/publications/',
        'aflt': 'https://www.finam.ru/quote/moex/aflt/publications/',
        'agrodr': 'https://www.finam.ru/quote/moex/agro/publications/',
        'alrs': 'https://www.finam.ru/quote/moex/alrs/publications/',
        'cbom': 'https://www.finam.ru/quote/moex/cbom/publications/',
        'chmf': 'https://www.finam.ru/quote/moex/chmf/publications/',
        'enpg': 'https://www.finam.ru/quote/moex/enpg/publications/',
        'fees': 'https://www.finam.ru/quote/moex/fees/publications/',
        'fivedr': 'https://www.finam.ru/quote/moex/five/publications/',
        'flot': 'https://www.finam.ru/quote/moex/flot/publications/',
        'gazp': 'https://www.finam.ru/quote/moex/gazp/publications/',
        'gltrdr': 'https://www.finam.ru/quote/moex/gltr/publications/',
        'gmkn': 'https://www.finam.ru/quote/moex/gmkn/publications/',
        'hydr': 'https://www.finam.ru/quote/moex/hydr/publications/',
        'irao': 'https://www.finam.ru/quote/moex/irao/publications/',
        'lkoh': 'https://www.finam.ru/quote/moex/lkoh/publications/',
        'magn': 'https://www.finam.ru/quote/moex/magn/publications/',
        'mgnt': 'https://www.finam.ru/quote/moex/mgnt/publications/',
        'msng': 'https://www.finam.ru/quote/moex/msng/publications/',
        'mtlr': 'https://www.finam.ru/quote/moex/mtlr/publications/',
        'mtss': 'https://www.finam.ru/quote/moex/mtss/publications/',
        'nlmk': 'https://www.finam.ru/quote/moex/nlmk/publications/',
        'nvtk': 'https://www.finam.ru/quote/moex/nvtk/publications/',
        'ozondr': 'https://www.finam.ru/quote/moex/ozon/publications/',
        'phor': 'https://www.finam.ru/quote/moex/phor/publications/',
        'pikk': 'https://www.finam.ru/quote/moex/pikk/publications/',
        'plzl': 'https://www.finam.ru/quote/moex/plzl/publications/',
        'poly': 'https://www.finam.ru/quote/moex/poly/publications/',
        'posi': 'https://www.finam.ru/quote/moex/posi/publications/',
        'rosn': 'https://www.finam.ru/quote/moex/rosn/publications/',
        'rtkm': 'https://www.finam.ru/quote/moex/rtkm/publications/',
        'rual': 'https://www.finam.ru/quote/moex/rual/publications/',
        'sber': 'https://www.finam.ru/quote/moex/sber/publications/',
        'selg': 'https://www.finam.ru/quote/moex/selg/publications/',
        'sgzh': 'https://www.finam.ru/quote/moex/sgzh/publications/',
        'smlt': 'https://www.finam.ru/quote/moex/smlt/publications/',
        'sngs': 'https://www.finam.ru/quote/moex/sngs/publications/',
        'tatn': 'https://www.finam.ru/quote/moex/tatn/publications/',
        'tcsg': 'https://www.finam.ru/quote/moex/tcsg/publications/',
        'trnf_p': 'https://www.finam.ru/quote/moex/trnfp/publications/',
        'upro': 'https://www.finam.ru/quote/moex/upro/publications/',
        'vkco': 'https://www.finam.ru/quote/moex/vkco/publications/',
        'vtbr': 'https://www.finam.ru/quote/moex/vtbr/publications/',
        'yndx': 'https://www.finam.ru/quote/moex/yndx/publications/',
        'qiwidr': 'https://www.finam.ru/quote/moex/qiwi/publications/',
        'trmk': 'https://www.finam.ru/quote/moex/trmk/publications/',
        'akrn': 'https://www.finam.ru/quote/moex/akrn/publications/',
        'mgmdr': 'https://www.finam.ru/quote/moex/mdmg/publications/',
        'utar': 'https://www.finam.ru/quote/moex/utar/publications/'
}


synonimus     = {'afks': ['афк систем', 'афк', 'система ао'], 'aflt': ['аэрофлот'], 'agrodr': ['русагро'], 'alrs': ['алроса'],
                 'cbom': ['московский кредитный банк', 'мкб'], 'chmf': ['северстал'], ' enpg ': ['эн', 'en', 'энел'],
                 'fees': ['фск', 'россет'], 'fivedr': ['x5'], 'flot': ['совкомфлот'], 'gazp': ['газпром'],
                 'gltrdr': ['глобалтранс', 'globaltrans'], 'gmkn': ['норникел'], 'hydr': ['русгидр'], 'irao': ['интер'],
                 'lkoh': ['лукойл'], 'magn': ['ммк'], 'mgnt': ['магнит'], 'msng': ['мосэнерго'], 'mtlr': ['мечел'],
                 'mtss': ['мтс'], 'nlmk': ['нлмк'], 'nvtk': ['новатэк'], 'ozondr': ['озон'], 'phor': ['фосагро'],
                 'pikk': ['пик'], 'plzl': ['полюс'], 'poly': ['полиметал'], 'posi': ['позитив'], 'rosn': ['роснефть'],
                 'rtkm': ['ростелеком'], 'rual': ['русал'], 'sber': ['сбер'], 'selg': ['селигдар'], 'sgzh': ['сегеж'],
                 'smlt': ['самолет'], 'sngs': ['сургутнетфегаз'], 'tatn': ['татнефть'], 'tcsg': ['тинькофф'],
                 'trnf_p': ['трансефт'], 'upro': ['юнипро'], 'vkco': ['вконтакт', 'vk'], 'vtbr': ['втб', 'vtb'],
                 'yndx': ['яндекс', 'yandex'], 'qiwidr': ['киви', 'qiwi'], 'trmk': ['тмк'], 'akrn': ['акрон'],
                 'mgmdr': ['мать и дитя'], 'utar': ['ютэйр', 'utair']}